# Installs and configures InfluxDB to be a host for Telegraf metrics
# and to let Chronograf and Kapacitor connect to it with their own users

- name: Install InfluxDB package
  apt:
    name: influxdb
    state: present

- name: Create InfluxDB data dir with correct permissions
  file:
    name: "{{ influxdb_data_dir }}"
    owner: influxdb
    group: influxdb
    mode: 0755
    state: directory

- name: Stop the InfluxDB server before configuration/restore
  service:
    name: influxdb
    state: stopped

- name: Configure InfluxDB (also enables auth)
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf

- name: Use backup for setting up users/DBs settings (intead of creating them with Ansible)
  copy:
    src: '{{ influxdb_meta_backup }}'
    dest: '/home/ubuntu/backup/'
  when: influxdb_meta_backup is defined

- shell: influxd restore -metadir {{ influxdb_meta_dir }} /home/ubuntu/backup/
  when: influxdb_meta_backup is defined
  register: restore_output

- name: Restore output
  debug:
    var: restore_output
  when: influxdb_meta_backup is defined

- name: Start the InfluxDB server before to using it in the next steps
  service:
    name: influxdb
    enabled: yes
    state: started

- name: Create InfluxDB admin user
  influxdb_user:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    # User setup:
    user_name:      "{{ influxdb_admin_user }}"
    user_password:  "{{ influxdb_admin_pw }}"
    admin: true
    retries: 3
    state: present
  when: influxdb_meta_backup is undefined

- name: Create telegraf and chronograf DBs
  influxdb_database:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    username:       "{{ influxdb_admin_user }}"
    password:       "{{ influxdb_admin_pw }}"
    # DB setup:
    database_name:  "{{ item }}"
    state: present
  with_items:
    - "{{ influxdb_telegraf_db }}"
    - "{{ influxdb_chronograf_db }}"
  when: influxdb_meta_backup is undefined

- name: Create retention policy for telegraf DB
  influxdb_retention_policy:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    username:       "{{ influxdb_admin_user }}"
    password:       "{{ influxdb_admin_pw }}"
    database_name:  "{{ influxdb_telegraf_db }}"
    # policy setup:
    policy_name: "{{ telegraf_retention_policy_name }}"
    duration: "{{ telegraf_retention_time }}"
    replication: 1
    default: true
  when: influxdb_meta_backup is undefined

- name: Create InfluxDB chronograf user for Chronograf app access
  influxdb_user:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    username:       "{{ influxdb_admin_user }}"
    password:       "{{ influxdb_admin_pw }}"
    # User setup:
    user_name:      "{{ influxdb_chronograf_user }}"
    user_password:  "{{ influxdb_chronograf_pw }}"
    state: present
  when: influxdb_meta_backup is undefined

- name: Grant access to telegraf and chronograf DBs for chronograf user
  influxdb_query:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    username:       "{{ influxdb_admin_user }}"
    password:       "{{ influxdb_admin_pw }}"
    # GRANT access query:
    query: "GRANT ALL ON {{ item }} TO {{ influxdb_chronograf_user }}"
  with_items:
    - "{{ influxdb_telegraf_db }}"
    - "{{ influxdb_chronograf_db }}"
  when: influxdb_meta_backup is undefined

- name: Create InfluxDB user for the telegraf agents
  influxdb_user:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    username:       "{{ influxdb_admin_user }}"
    password:       "{{ influxdb_admin_pw }}"
    # User setup:
    user_name:      "{{ influxdb_telegraf_user }}"
    user_password:  "{{ influxdb_telegraf_pw }}"
    state: present
  when: influxdb_meta_backup is undefined

- name: Grant access to telegraf user to WRITE to telegraf DB
  influxdb_query:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    username:       "{{ influxdb_admin_user }}"
    password:       "{{ influxdb_admin_pw }}"
    # GRANT access query:
    query: "GRANT WRITE ON {{ influxdb_telegraf_db }} TO {{ influxdb_telegraf_user }}"
  when: influxdb_meta_backup is undefined
