# Installs and configures Chronograf the Webapp for InfluxDB

- name: Install chronograf package
  ansible.builtin.apt:
    name: chronograf
    state: present

- name: Stop Chronograf
  ansible.builtin.service:
    name: chronograf
    state: stopped

- name: Configure startup params (overwriting default init script ENV variables)
  ansible.builtin.template:
    src: chronograf_defaults.j2
    dest: /etc/default/chronograf

- name: Restore config DB for Chronograf to usual location
  ansible.builtin.copy:
    src: '{{ influxdb_chronograf_db_backup }}'
    dest: /var/lib/chronograf/chronograf-v1.db
    owner: chronograf
    group: chronograf
  when: influxdb_chronograf_db_backup is defined

- name: Start Chronograf
  ansible.builtin.service:
    name: chronograf
    enabled: yes
    state: started
