# Installs and configures InfluxDB to be a host for Telegraf metrics
# and to let Chronograf and Kapacitor connect to it with their own users

- name: Install InfluxDB package
  apt:
    name: influxdb
    state: present

- name: Configure InfluxDB (also enables auth)
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify:
    - 'restart influxdb'

# As handlers only run at the end of a play we can't rely on the notify of
# the previous task, as we need InfluxDB running for the next task already.
- name: Restart the InfluxDB before moving on
  service:
    name: influxdb
    enabled: yes
    state: restarted

- name: Create InfluxDB admin user
  influxdb_user:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    # User setup:
    user_name:      "{{ influxdb_admin_user }}"
    user_password:  "{{ influxdb_admin_pw }}"
    admin: true
    state: present

- name: Create telegraf and chronograf DBs
  influxdb_database:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    username:       "{{ influxdb_admin_user }}"
    password:       "{{ influxdb_admin_pw }}"
    # DB setup:
    database_name:  "{{ item }}"
    state: present
  with_items:
    - "{{ influxdb_telegraf_db }}"
    - "{{ influxdb_chronograf_db }}"

- name: Create retention policy for telegraf DB
  influxdb_retention_policy:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    username:       "{{ influxdb_admin_user }}"
    password:       "{{ influxdb_admin_pw }}"
    database_name:  "{{ influxdb_telegraf_db }}"
    # policy setup:
    policy_name: "{{ telegraf_retention_policy_name }}"
    duration: "{{ telegraf_retention_time }}"
    replication: 1
    default: true

- name: Create InfluxDB chronograf user for Chronograf app access
  influxdb_user:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    username:       "{{ influxdb_admin_user }}"
    password:       "{{ influxdb_admin_pw }}"
    # User setup:
    user_name:      "{{ influxdb_chronograf_user }}"
    user_password:  "{{ influxdb_chronograf_pw }}"
    state: present

- name: Grant access to telegraf and chronograf DBs for chronograf user
  influxdb_query:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    username:       "{{ influxdb_admin_user }}"
    password:       "{{ influxdb_admin_pw }}"
    # GRANT access query:
    query: "GRANT ALL ON {{ item }} TO {{ influxdb_chronograf_user }}"
  with_items:
    - "{{ influxdb_telegraf_db }}"
    - "{{ influxdb_chronograf_db }}"

- name: Create InfluxDB user for the telegraf agents
  influxdb_user:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    username:       "{{ influxdb_admin_user }}"
    password:       "{{ influxdb_admin_pw }}"
    # User setup:
    user_name:      "{{ influxdb_telegraf_user }}"
    user_password:  "{{ influxdb_telegraf_pw }}"
    state: present

- name: Grant access to telegraf user to WRITE to telegraf DB
  influxdb_query:
    # Connection details:
    hostname:       "{{ influxdb_host }}"
    port:           "{{ influxdb_port }}"
    username:       "{{ influxdb_admin_user }}"
    password:       "{{ influxdb_admin_pw }}"
    # GRANT access query:
    query: "GRANT WRITE ON {{ influxdb_telegraf_db }} TO {{ influxdb_telegraf_user }}"
