---
# tasks file for mediafellows.influxdb

# Installs influxdata repo and key:

- name: Import InfluxData apt package signing key
  ansible.builtin.shell:
    cmd: curl -fsSL {{ influxdb_repo_base_url }}/influxdata-archive_compat.key|sudo gpg --dearmor -o /usr/share/keyrings/influxdb-keyring.gpg

- name: Add InfluxData repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/influxdb-keyring.gpg] {{ influxdb_repo_base_url }}/{{ ansible_distribution | lower }} stable main
    state: present

- name: Update apt index
  ansible.builtin.apt:
    update_cache: true

- name: Install influxdb python binding in order to user the Ansible influxdb_database module
  ansible.builtin.apt:
    name: python-influxdb
    state: present
  when: ansible_python_version <= '3.0'

- ansible.builtin.apt:
    name: python3-influxdb
    state: present
  when: ansible_python_version >= '3.0'

# Install and configure each component:

- ansible.builtin.import_tasks: install_influxdb.yml
  when: influxdb_install_influxdb

- ansible.builtin.import_tasks: install_chronograf.yml
  when: influxdb_install_chronograf

- ansible.builtin.import_tasks: install_kapacitor.yml
  when: influxdb_install_kapacitor
