---
# tasks file for mediapeers.influxdb

# Fixes for older distros with old python to allow HTTPs downloads from servers using SNI:

- name: Install python-pip in order to install some python packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip

- name: Install Python packages needed to fix downloading from https urls on older distros/python versions (needed for next tasks)
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - urllib3
    - ndg-httpsclient
    - pyOpenSSL
    - pyasn1
  when:
    (ansible_distribution == 'Ubuntu' and ansible_distribution_version < '15.04') or
    (ansible_distribution == 'Debian' and ansible_distribution_version < '8')

# Installs influxdata repo and key:

- name: Import InfluxData GPG signing key
  apt_key:
    url: "{{ influxdb_repo_base_url }}/influxdb.key"
    state: present

- name: Add InfluxData repository
  apt_repository:
    repo: deb {{ influxdb_repo_base_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ influxdb_install_version }}
    state: present

- name: Update apt index
  apt:
    update_cache: true


# Install and configure each component:

- include: install_influxdb.yml
  when: influxdb_install_influxdb

- include: install_chronograf.yml
  when: influxdb_install_chronograf

- include: install_kapacitor.yml
  when: influxdb_install_kapacitor

