---
# handlers file for mediafellows.influxdb

- name: restart influxdb
  ansible.builtin.service:
    name: influxdb
    enabled: yes
    state: restarted

- name: restart chronograf
  ansible.builtin.service:
    name: chronograf
    enabled: yes
    state: restarted

- name: restart kapacitor
  ansible.builtin.service:
    name: kapacitor
    enabled: yes
    state: restarted
