---
# handlers file for mediapeers.influxdb

- name: restart influxdb
  service:
    name: influxdb
    enabled: yes
    state: restarted

- name: restart chronograf
  service:
    name: chronograf
    enabled: yes
    state: restarted

- name: restart kapacitor
  service:
    name: kapacitor
    enabled: yes
    state: restarted
